cmake_minimum_required(VERSION 3.28)
project(YandexHomeSdkExample LANGUAGES CXX)
find_package(YandexHome CONFIG REQUIRED COMPONENTS AppServices AuthCore YandexApiAdapter AppCli)
add_executable(yh-sdk-example main.cpp)
target_link_libraries(yh-sdk-example PRIVATE YandexHome::AppServices
  YandexHome::AuthCore YandexHome::YandexApiAdapter YandexHome::AppCli)
if(TARGET YandexHome::AppRest)
  find_package(YandexHome CONFIG REQUIRED COMPONENTS AppRest)
  target_compile_definitions(yh-sdk-example PRIVATE YH_EXAMPLE_REST)
  target_link_libraries(yh-sdk-example PRIVATE YandexHome::AppRest)
endif()
enable_testing()
add_test(NAME SdkExample COMMAND yh-sdk-example)
