# Exercise the actual entry point with no stored credentials or live requests.
function(check_cli expected)
  execute_process(COMMAND "${APP_PATH}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
  if(NOT "${result}" STREQUAL "${expected}")
    message(FATAL_ERROR "Unexpected exit (${ARGN}): ${result}, expected ${expected}\n${output}${error}")
  endif()
  if(expected EQUAL 0)
    if(NOT error STREQUAL "")
      message(FATAL_ERROR "Success polluted stderr: ${error}")
    endif()
    set(json "${output}")
    set(expected_ok ON)
  else()
    if(NOT output STREQUAL "")
      message(FATAL_ERROR "Error polluted stdout: ${output}")
    endif()
    set(json "${error}")
    set(expected_ok OFF)
  endif()
  string(JSON ok ERROR_VARIABLE parse_error GET "${json}" ok)
  if(parse_error OR NOT "${ok}" STREQUAL "${expected_ok}")
    message(FATAL_ERROR "Invalid JSON response (${ARGN}): ${json}")
  endif()
  set(response "${json}" PARENT_SCOPE)
endfunction()

check_cli(0 --help --json)
string(JSON help GET "${response}" help)
if(NOT help MATCHES "devices set" OR NOT help MATCHES "scenarios run")
  message(FATAL_ERROR "Help does not describe registered commands")
endif()
check_cli(2 nonsense --json)
string(JSON code GET "${response}" error code)
if(NOT code STREQUAL "usage")
  message(FATAL_ERROR "Parse errors must have the stable usage code")
endif()
# Confirmation/validation must happen before keychain or API access.
check_cli(2 reset --json)
check_cli(2 devices set --id lamp --capability range --instance brightness --value nan --json)

if(CONFIGURATION STREQUAL "Debug")
  check_cli(0 --fake-api devices list --json)
  string(JSON count LENGTH "${response}" devices)
  if(NOT count EQUAL 3)
    message(FATAL_ERROR "Fixture device list is incomplete")
  endif()
  check_cli(0 --fake-api devices show --id lamp --json)
  string(JSON id GET "${response}" device id)
  if(NOT id STREQUAL "lamp")
    message(FATAL_ERROR "CLI selected the wrong device")
  endif()
  check_cli(0 --fake-api --list-devices --json)
  check_cli(0 --fake-api account show --json)
  check_cli(0 --fake-api scenarios list --json)
  check_cli(0 --fake-api scenarios run --id evening --json)
  check_cli(1 --fake-api scenarios run --id failure --json)
  check_cli(2 --fake-api scenarios run --id inactive --json)
  check_cli(4 --fake-api scenarios run --id missing --json)
  check_cli(4 --fake-api devices show --name missing --json)
  # The read-only fixture deliberately refuses device actions; never fake success.
  check_cli(1 --fake-api devices set --id lamp --capability on_off --value on --json)
  check_cli(5 --fake-api devices list --timeout 1 --json)
  check_cli(0 --fake-api reset --i-know-what-i-am-doing --json)
else()
  check_cli(2 --fake-api devices list --json)
endif()
