#!/usr/bin/env python3
"""Expose bundled JSON display strings to Qt Linguist's lupdate tool."""

import json
import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "resources" / "data"
OUTPUT = ROOT / "translations" / "DataStrings.cpp"

CATALOGS = {
    "DataColors": ("colors.json", {"name"}),
    "DataColorModes": ("colorModes.json", {"name"}),
    "DataModes": ("modes.json", {"name"}),
    "DataInstances": ("instances.json", None),
    "DataEvents": ("propertiesEvents.json", None),
    "DataUnits": ("units.json", None),
    "DataErrors": ("errorCodes.json", {"short_description", "full_description"}),
}


def strings(value, fields):
    if isinstance(value, list):
        for item in value:
            yield from strings(item, fields)
    elif isinstance(value, dict):
        for key, item in value.items():
            if isinstance(item, str) and (fields is None or key in fields):
                yield item
            else:
                yield from strings(item, fields)


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--check", action="store_true", help="Fail if the committed marker file is stale")
args = parser.parse_args()

lines = [
    "// Generated by scripts/update-data-translation-markers.py. Do not edit by hand.",
    "// This file is scanned by lupdate; it is not compiled into the app.",
    "#include <QCoreApplication>",
    "",
]

for context, (filename, fields) in CATALOGS.items():
    data = json.loads((DATA / filename).read_text(encoding="utf-8"))
    lines.append(f"static const char *const k{context}[] = {{")
    for source in dict.fromkeys(strings(data, fields)):
        lines.append(
            f'  QT_TRANSLATE_NOOP("{context}", {json.dumps(source, ensure_ascii=False)}),'
        )
    lines.extend(["};", ""])

generated = "\n".join(lines)
if args.check:
    if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
        parser.exit(1, "Translation markers are stale. Run scripts/update-data-translation-markers.py\n")
else:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
